default_view: "List functions"
views:
  "List functions":
    1:
      text: next view
      view: "NPM functions"
    2:
      text: ls
      command: ls
    3:
      text: ll
      command: ll
    4:
      text: la
      command: la
  "NPM functions":
    1:
      text: next view
      view: "Git functions"
    2:
      text: ls
      command: npm ls
  "Git functions":
    1:
      text: next view
      view: "List functions"
    2:
      text: status
      command: git status
